### ISSUE TITLE
Request for export of TQFP32-08 model files

### ISSUE THREAD

**Issue by follower** [sparkfun/3D_Models#178]
The `TQFP32-08` variant (used by e.g. the RedStick) doesn't have exported models in the repository--only the source file [`TQFP32-08.skp`](https://github.com/sparkfun/3D_Models/blob/master/production_parts/semiconductors/IC_SMD/TQFP/TQFP32-08.skp) is present.

Could someone please export the models and add them to the repository (like the [`TQFP-48`]( https://github.com/sparkfun/3D_Models/tree/master/production_parts/semiconductors/IC_SMD/TQFP/TQFP-48) part has). My specific interest is in the `.stl` format.

Thanks.

**Comment by follower** [comment]
FWIW it seems this model is possibly equivalent: https://github.com/sparkfun/3D_Models/blob/master/products/9261/stl/9261.STL ([via](https://www.sparkfun.com/products/retired/9261))

**Comment by follower** [comment]
Further investigation into the repository content suggests that there are multiple models that are only present in form of the SketchUp file. Are there any plans to export a consistent set of formats for each model?

**Comment by elizabethsrobert** [comment]
Thank you so much for your message! All of our models in the `Products` folder will typically have a consistent set of formats. A good example would be this:

[Product 9393](https://github.com/sparkfun/3D_Models/tree/master/products/9393)

Individual components used to build up those products are housed in the `Production_Parts` folder and will normally only have a .SKP file. Where I'd say 95% of our product models are made from scratch, through a combination of Solidworks, SketchUp, and Blender, there are some cases where we use preexisting models. That tends to be more of the case in regards to the `Production_Parts` folder since it is a collection of individual components solely used to populate our larger models found in the `Products` folder. When populating our 3D models for our SparkFun specific boards, the only requirement is to have the .SKP file which is why you'll rarely find other formats in that folder unless they've been made from scratch.

That being said, I can definitely talk to some people here at SparkFun to see if they would be on board with supplying other formats within our `Production_Parts` folder. In the meantime though, I'll be more than happy to add the `TQFP32-08.stl` format for you. I'll comment back when it is complete.

**Comment by elizabethsrobert** [comment]
The `TQFP32-08.stl` you requested can now be located in the following folder: [TQFP32-08](https://github.com/sparkfun/3D_Models/tree/master/production_parts/semiconductors/IC_SMD/TQFP/TQFP32-08).

It seems, at this time, we will not be adding other formats to our `Production_Parts` folder as it is purely utilized to aide in building our 3D models for the storefront. That being said, we will always supply multiple formats to our `Products` folder, and any requests we get to supply additional formats for components in the `Production_Parts` folder we will have no problem fulfilling.

If you have any further questions please let me know. Thank you for your inquiry!

**Comment by follower** [comment]
Thanks for your detailed reply and exporting the TQFP part for me, I appreciate you taking the time to do so (even though it's taken a long time to get back to you!).

For a client project (https://github.com/Omniblox/Eagle-Loader) I wrote a script to automate generation of  `.stl` files from the SparkFun SketchUp models: <https://github.com/Omniblox/pcb-component-models/blob/master/tools/generate_missing_stl.rb>

These generated models are currently in my fork of the `3D_Models` repo here: <https://github.com/follower/3D_Models/tree/batch-stl-export>. (And in a standalone model "library" used by `Eagle-Loader` here: <https://github.com/Omniblox/pcb-component-models>.)

Would SparkFun be interested in a PR with the additional exported models?

Thanks again for your assistance and providing the models.

**Comment by zinefer** [comment]
We'd be happy to accept your PR.
